services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=pyta
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pyta"]
      interval: 30s
      timeout: 10s
      retries: 5
    # volumes:
    #   - db_vol

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  app:
    restart: always
    depends_on:
      - db
    build:
      context: ./backend/.
      args:
        - SKIP_TESTS=true
    env_file:
      - ./backend/.env
    
    ports:
      - "${BACKEND_PORT}:8000"

  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "${FRONTEND_PORT}:3000"

# volumes:
#   db_vol: