#!/bin/sh
poetry --directory ./backend run ruff check $(git diff --name-only --cached --diff-filter=ACM -- '*.py') --config ./backend/pyproject.toml --fix
poetry --directory ./backend run ruff format ./backend/.
poetry --directory ./backend run mypy . --config-file ./backend/pyproject.toml

cd frontend || exit
npx @biomejs/biome check --staged --files-ignore-unknown=true --no-errors-on-unmatched --fix

cd .. || exit
git add $(git diff --name-only --cached --diff-filter=ACM -- '*.*')
